-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Products Table (Create if not exists)
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price decimal(10,2) not null,
  image_url text,
  category text not null,
  sizes text[] default '{}'::text[],
  description text,
  variants jsonb default '[]'::jsonb, -- [{ "size": "M", "color": "Red", "stock": 10 }]
  active boolean default true
);

-- Profiles Table (Create if not exists)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  first_name text,
  last_name text,
  email text,
  role text default 'customer', -- 'admin', 'ceo', 'sales'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Orders Table (for Sales Analytics)
create table if not exists orders (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id),
  total_amount decimal(12, 2) not null,
  status text default 'pending', -- pending, paid, shipped, cancelled
  items jsonb, -- Snapshot of items bought
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Audit Logs (for Edits)
create table if not exists audit_logs (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id),
  action text not null, -- 'create_product', 'update_stock', 'login'
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Page Visits (Simple Analytics)
create table if not exists page_analytics (
  id uuid default uuid_generate_v4() primary key,
  page_path text not null,
  visit_count integer default 0,
  last_visited_at timestamp with time zone default timezone('utc'::text, now()),
  unique(page_path)
);

-- Policies (RLS)
-- Enable RLS
alter table products enable row level security;
alter table orders enable row level security;
alter table audit_logs enable row level security;
alter table profiles enable row level security;

-- Products: Everyone can view, only Admin can edit
create policy "Public products view" on products for select using (true);
create policy "Admins can insert products" on products for insert with check (auth.email() like '%@febeflo.com');
create policy "Admins can update products" on products for update using (auth.email() like '%@febeflo.com');
create policy "Admins can delete products" on products for delete using (auth.email() like '%@febeflo.com');

-- Profiles: Users see own, Admins see all
create policy "Public profiles view" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Audit Logs: Only Admins can view and insert
create policy "Admins view logs" on audit_logs for select using (auth.email() like '%@febeflo.com');
create policy "Admins insert logs" on audit_logs for insert with check (auth.email() like '%@febeflo.com');

-- Orders: Users see own, Admins see all
create policy "Users see own orders" on orders for select using (auth.uid() = user_id);
create policy "Admins see all orders" on orders for select using (auth.email() like '%@febeflo.com');

-- STORAGE SETUP (Run this in SQL Editor)
-- Create buckets
insert into storage.buckets (id, name, public) values ('products', 'products', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict (id) do nothing;

-- Storage Policies (Requires manual setup in Dashboard usually, but SQL works if run as admin)
-- Note: Policies on storage.objects are complex to script if not superuser, but here is the intent:
-- create policy "Public Access Products" on storage.objects for select using ( bucket_id = 'products' );
-- create policy "Admin Upload Products" on storage.objects for insert with check ( bucket_id = 'products' and auth.email() like '%@febeflo.com' );
