-- Script SQL para configurar la base de datos en Supabase para Febeflo

-- 1. Crear tabla de Perfiles (Usuarios)
-- Esta tabla extiende la funcionalidad de auth.users de Supabase
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'customer', -- 'admin' o 'customer'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar RLS (Row Level Security) para perfiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- 2. Crear tabla de Productos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price integer not null, -- Precio en pesos chilenos (CLP)
  category text not null, -- 'mujer', 'hombre', 'ninos'
  image_url text,
  sizes text[] default '{}', -- Array de tallas disponibles
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar RLS para productos
alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on public.products for select
  using ( true );

create policy "Only admins can insert products."
  on public.products for insert
  with check ( exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can update products."
  on public.products for update
  using ( exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can delete products."
  on public.products for delete
  using ( exists ( select 1 from public.profiles where id = auth.uid() and role = 'admin' ) );

-- 3. Crear Trigger para crear perfil automáticamente al registrarse
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'customer');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. Datos de ejemplo (Opcional)
insert into public.products (name, description, price, category, stock, sizes)
values
  ('Vestido de Verano', 'Vestido ligero y fresco.', 15990, 'mujer', 10, ARRAY['S', 'M', 'L']),
  ('Jeans Slim Fit', 'Jeans cómodos y modernos.', 24990, 'hombre', 15, ARRAY['38', '40', '42', '44']),
  ('Polera Estampada', 'Polera divertida para niños.', 9990, 'ninos', 20, ARRAY['4', '6', '8', '10']);
